.build_template: &build_definition
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: build
  tags:
    - docker
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"credsStore\":\"ecr-login\"}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $REPOSITORY_URL:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA-$CI_PIPELINE_ID

variables:
  REPOSITORY_URL: $ECR_URL_PRE/<%= name %>

stages:
  - lint
  - test
  - build
  <% if(useSpinnaker) { %>- notify-spinnaker<% } %>

eslint:
  stage: lint
  tags:
    - microservices
  before_script:
    - npm i
  script:
    # Run ESLint
    - node ./node_modules/eslint/bin/eslint "{src,apps,libs,test}/**/*.ts"
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "web"

test:
  stage: test
  tags:
    - microservices
  before_script:
    - npm i
  script:
    - npm run test
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "web"

build:staging:
  <<: *build_definition
  before_script:
    - cat $ENV_STAGING > .env
  rules:
    - if: $CI_COMMIT_REF_SLUG =~ /^dev(elopment)?$/
    - if: $CI_PIPELINE_SOURCE == "triggers" || $CI_PIPELINE_SOURCE == "api"

build:production:
  <<: *build_definition
  before_script:
    - cat $ENV_PRODUCTION > .env
  rules:
    - if: $CI_COMMIT_REF_SLUG !~ /^master?$/ && $CI_COMMIT_TAG == null
      when: never
    - if: $CI_PIPELINE_SOURCE == "web"

<% if(useSpinnaker) { 
%>notify-spinnaker:
  image:
    name: curlimages/curl:latest
    entrypoint: [""]
  stage: notify-spinnaker
  tags:
    - docker
  script:
    - curl --location --request POST "https://api.spinnaker.rebellionpay.com/webhooks/webhook/ms-payments" --header "Content-Type:application/json" --data-raw "{\"dockerImage\":\""${REPOSITORY_URL}":"${CI_COMMIT_REF_SLUG}"-"${CI_COMMIT_SHORT_SHA}"-"${CI_PIPELINE_ID}"\", \"gitlabUrl\":\""${CI_API_V4_URL}"\",\"projectId\":\""${CI_PROJECT_ID}"\", \"pipelineId\":\""${CI_PIPELINE_ID}"\", \"ref\":\""${CI_COMMIT_REF_NAME}"\", \"commitSHA\":\""${CI_COMMIT_SHA}"\", \"launchedBy\":\""${ORIGINAL_USER}"\"}"
  rules:
    - if: $CI_COMMIT_REF_SLUG =~ /^dev(elopment)?$/
    - if: $CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "triggers" || $CI_PIPELINE_SOURCE == "api"
<% } %>